name: Deploy to Salesforce

on:
  push:
    branches:
      - main # Change this to your main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Salesforce CLI
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install Salesforce CLI
        run: npm install -g sfdx-cli

      - name: Authenticate with Salesforce
        run: sfdx force:auth:web:login -a myorg

      - name: Deploy to Salesforce
        run: sfdx force:source:deploy -p force-app -u myorg

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
